FROM prom/prometheus
ADD ../configs/prometheus.yml /etc/prometheus/


RUN chown prom /prometheus
USER prom

CMD [ "--config.file=/etc/prometheus/prometheus.yml", \
      "--storage.tsdb.path=/prometheus", \
      "--web.console.libraries=/usr/share/prometheus/console_libraries", \
      "--web.console.templates=/usr/share/prometheus/consoles", \
      "--storage.tsdb.retention.time=4d" ]